#########################################
# Install Clair scripts in the directory
#########################################
- name: Create target folder
  file:
    path: /home/ubuntu/clair-container-scan
    state: directory

- name: Distribute shell script file
  template: src=templates/container-scan.sh.j2 dest=/home/ubuntu/clair-container-scan/container-scan.sh mode=0744

- name: Execute the script
  shell: ./container-scan.sh
  args:
    chdir: /home/ubuntu/clair-container-scan/

# - name: Get owner email detail from Docker Image's LABELS

# - name: Send notification to the owner
