---
region: <region>
validate_certs: <validate_certs, yes | no>
auth_url: <auth_url>
project_name: <project_name>
username: <username>
password: <password>
project_domain_name: <project_domain_name>
user_domain_name: <user_domain_name>
